name: "Build"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '51 2 * * 0'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout data branch
      uses: actions/checkout@v2
      with:
        ref: iana-numbers
        path: out
        fetch-depth: 0
    - name: Create new iana-etc releases
      run: ./ci/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
